#! /usr/local/env python

import os
import sys

def __directoryName(ctx):
	return os.path.basename(os.path.dirname(ctx.path.abspath()))

def options(ctx):
	pass

def configure(ctx):
	ctx.msg("Configuring", __directoryName(ctx), color="YELLOW")
	ctx.msg("Compiler", ctx.env.CXX_NAME, color="BLUE")

	ctx.define("BINARY_NAME", __directoryName(ctx))

def build(bld):
	bld.program(source=bld.path.ant_glob("*.cpp"),
				target="analyser-common",
				includes=["."])
